import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: {
  children: React.ReactNode;
  analytics: React.ReactNode;
  team: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='default-layout'>{props.children}</div>
        <div className='analytics'>{props.analytics}</div>
        <div className='team'>{props.team}</div>
      </body>
    </html>
  )
}
